apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-argocd
spec:
  selector:
    app.kubernetes.io/name: nginx-pod
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
