apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: nginx-argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: 192.168.127.131:32000/nginx
