apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi # 필요에 따라 스토리지 용량을 조절하세요.
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # PV 삭제 시 데이터 보존 정책 (Delete, Recycle, Retain)
  nfs:
    server: 192.168.127.131 # NFS 서버의 IP 주소 또는 호스트 이름으로 변경하세요.
    path: /nfs_shared/mysql # NFS 서버의 공유 경로
  claimRef: # 특정 PVC에 바인딩되도록 명시
    name: mysql-pvc # 허용할 PVC의 이름
    namespace: mysql # PVC가 위치한 네임스페이스 (기본값은 default)