# app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kshelp/kube.git
    targetRevision: HEAD
    path: Resources/App
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

