apiVersion: apps/v1
kind: Deployment              
metadata:              
  name: rolling
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: rolling
    spec:    
      containers:
      - name: rolling
        image: myimage
        ports:
        - containerPort: 8080
