apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.127.131 # NFS 서버의 IP 주소 또는 호스트 이름으로 변경하세요.
    path: /nfs_shared/registry # NFS 서버의 공유 경로
  claimRef: # 특정 PVC에 바인딩되도록 명시
    name: registry-pvc # 허용할 PVC의 이름
    namespace: registry # PVC가 위치한 네임스페이스 (기본값은 default)
