---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;

        location /static/ {
            alias /static/;
        }

        location / {
            proxy_pass http://localhost:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: static-volume
          emptyDir: {}
      containers:
        - name: django-app
          image: 192.168.127.131:32000/django-app
          command: ["/bin/sh", "-c"]
          args:
            - |
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "0"
            - name: DB_HOST
              value: "192.168.127.250"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "book_ex"
            - name: DB_USER
              value: "zerock"
            - name: DB_PASSWORD
              value: "zerock"
            - name: CSRF_TRUSTED_ORIGINS
              value: "http://192.168.127.249:8000,http://localhost:8000"
          volumeMounts:
            - name: static-volume
              mountPath: /app/www_dir/static

        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: static-volume
              mountPath: /static

---
apiVersion: v1
kind: Service
metadata:
  name: django-svc
spec:
  selector:
    app: django
  type: LoadBalancer
  loadBalancerIP: 192.168.127.249
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
