---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: 192.168.127.131:32000/react-app # 여기에서 React 프로젝트의 이미지로 변경
          #command: ["sh", "-c", "cd /099 && npm install && npm start"]
          ports:
            - containerPort: 80

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

