apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: 3-replicaset # 레플리카 이름
spec:
  template:
    metadata:
      name: 3-replicaset
      labels:
        app: 3-replicaset
    spec:
      containers:
      - name: 3-replicaset
        image: nginx
        ports:
        - containerPort: 80
  replicas: 3 # 3개의 파드 생성
  selector:
    matchLabels:
      app: 3-replicaset