# Generated by Django 5.2 on 2025-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
